cache: pip
install: pip install .[ci,test]
jobs:
  include:
    - install: pip install .[lint]
      python: 3.8
      script:
        - black --check --verbose *.py prawtools tests
        - flake8
        - pydocstyle
      stage: lint
language: python
matrix:
  fast_finish: true
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
script:
  - coverage run --source=prawtools --module pytest
stages:
  - lint
  - test
