after_success: coveralls
cache: pip
install: pip install coveralls black flake8 pydocstyle
language: python
matrix:
  fast_finish: true
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
script:
  - black --check --verbose *.py prawtools tests
  - flake8
  - pydocstyle
  - coverage run --source=prawtools setup.py test
sudo: false
