after_success: coveralls
cache: pip
install: pip install coveralls flake8 pydocstyle
language: python
matrix:
  fast_finish: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
script:
  - flake8
  - pydocstyle
  - coverage run --source=prawtools setup.py test
sudo: false
